### PR TITLE
Branch "development" since May 2021 

### PR DESCRIPTION
**Pull request by ralf-berger**
We have a huge amount of changes in a branch "development" that diverged from master in May 2021. This is an attempt to integrate all of it in one go.

### CODE REVIEW

**Comment by shoebjoarder** [comment]
The requirements.txt file is out-dated. You can use `pipenv` to install the packages from Pipfile.lock and then `pip freeze > requirements.txt` to generate the new requirements. If you like I can update the file and push it.

**Comment by ralf-berger** [comment]
> If you like I can update the file and push it.

Sure, go ahead!

**Comment by shoebjoarder** [comment]
Done. Just to give you a heads-up, we have updated node version from `8.9.0` to `12.13.0` for the frontend

**Review by ralf-berger — COMMENTED** [review]
Increases the number of Python dependencies from 69 to 235.

**Comment by ralf-berger** [comment]
Information received via email:

> 1. We do NOT need the GloVe model anymore, which means we no longer need to download it.
> 2. The files that need to be downloaded are mentioned in the "Installation Guide for RIMA-Backend" (steps 7 to 9). Just so you know – those files are required to be placed accordingly to the location mentioned. Let me know whether we need to update it using "os.path.abspath" to let the application find the files
> 3. In the example.env, you will notice a new environment variable. We need to add it to the deployment. The API key for the semantic scholar is as follows: […]

**Comment by rbq** [comment]
Issues tracking the [aforementioned email requests](#issuecomment-1630458332):
1. https://github.com/ude-soco/RIMA/issues/314
2. https://github.com/ude-soco/RIMA/issues/315
3. https://github.com/ude-soco/RIMA/issues/317

**Comment by ralf-berger** [comment]
Issues tracking the [aforementioned email requests](#issuecomment-1630458332):
1. https://github.com/ude-soco/RIMA/issues/314
2. https://github.com/ude-soco/RIMA/issues/315
3. https://github.com/ude-soco/RIMA/issues/317

**Comment by ralf-berger** [comment]
Information received in person:
* `development` shouldn't actually be merged but considered a fork for a certain limited use-case
* branch is required to build and run until Monday July 24th

**Pull request closed without merging**
